#!/bin/sh

# This acts as a shell for nremadd.

PERSFILE='/home/paulf/remind/paulf-only.rem'
GENFILE='/home/paulf/remind/general.rem'
EXECFILE='./nremadd'

# help
if ! [ -z $1 ]
then
    $EXECFILE $1
    exit
fi

{ RESULT=$($EXECFILE 2>&1 >&3 3>&-); } 3>&1
RETVAL=$?

if [ $RETVAL -eq 0 ]
then
    PERSONAL=$(echo $RESULT | awk -F'|' '{print $1}')
    DATE=$(echo $RESULT | awk -F'|' '{print $2}')
    WARN=$(echo $RESULT | awk -F'|' '{print $3}')
    TEXT=$(echo $RESULT | awk -F'|' '{print $4}')

    if [ "$PERSONAL" == "1" ]
    then
        if [ -z $WARN ]
        then
            echo "rem $DATE msg $TEXT" >> $PERSFILE
        else
            echo "rem $DATE +$WARN msg $TEXT %b" >> $PERSFILE
        fi
    else
        if [ -z $WARN ]
        then
            echo "rem $DATE msg $TEXT" >> $GENFILE
        else
            echo "rem $DATE +$WARN msg $TEXT %b" >> $GENFILE
        fi
    fi

    echo "SUCCESS: event saved"

elif [ $RETVAL -eq 1 ]
then
    echo "FAIL: bad user input"
elif [ $RETVAL -eq 2 ]
then
    echo "FAIL: user canceled"
fi

